### ISSUE TITLE
Refactorizar Caso 3

### ISSUE THREAD

**Issue by imaguila** [imaguila/Refactorizacion#16]

**Comment by AlejandroFrGU** [comment]
Hecho.

**Comment by imaguila** [comment]
Revisar overleaf.  Si refactoriazas el caso 3 debes colocarlo en el capitulo correspondiente al caso 3 no en tu proyecto, éste lo completará en tu caso Juan

**Comment by AlejandroFrGU** [comment]
Actualizado y hecho.
